export type Contributor = {
  username: string;
  avatarUrl: string;
};

/**
 * Attribution roll for the upstream work this project derives from — GitHub
 * contributors of gnoviawan/termul (MIT), generated by scripts/sync-contributors.ts.
 * Deliberately not repointed at this repository; see that script for why.
 */
export const contributors: Contributor[] = [
  {
    username: 'gnoviawan',
    avatarUrl: 'https://avatars.githubusercontent.com/u/72639723?v=4',
  },
  {
    username: 'davidyusaku-13',
    avatarUrl: 'https://avatars.githubusercontent.com/u/71997005?v=4',
  },
  {
    username: 'InvictusNavarchus',
    avatarUrl: 'https://avatars.githubusercontent.com/u/115978750?v=4',
  },
  {
    username: 'DeryFerd',
    avatarUrl: 'https://avatars.githubusercontent.com/u/114888155?v=4',
  },
  {
    username: 'laurensiusjonathan-ID',
    avatarUrl: 'https://avatars.githubusercontent.com/u/214809898?v=4',
  },
  {
    username: 'ajianaz',
    avatarUrl: 'https://avatars.githubusercontent.com/u/12648688?v=4',
  },
  {
    username: 'kaine-na',
    avatarUrl: 'https://avatars.githubusercontent.com/u/129574549?v=4',
  },
  {
    username: 'julianromli',
    avatarUrl: 'https://avatars.githubusercontent.com/u/203207881?v=4',
  },
  {
    username: 'leemuljadi',
    avatarUrl: 'https://avatars.githubusercontent.com/u/48749437?v=4',
  },
  {
    username: 'ihsan-ramadhan',
    avatarUrl: 'https://avatars.githubusercontent.com/u/121941162?v=4',
  },
  {
    username: 'mannnrachman',
    avatarUrl: 'https://avatars.githubusercontent.com/u/32955459?v=4',
  },
  {
    username: 'RudyCity',
    avatarUrl: 'https://avatars.githubusercontent.com/u/82188919?v=4',
  },
];
