/**
 * Sync landing/src/data/contributors.ts from the GitHub contributors API.
 * Excludes Cursor and Claude bot accounts from the public grid.
 *
 * Usage: bun scripts/sync-contributors.ts
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { isExcludedContributor } from '../src/lib/contributors';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(__dirname, '../src/data/contributors.ts');

// Intentionally still the original project. This grid is the attribution roll for the
// code this project is derived from (MIT); repointing it at qinsehm1128/termul-new
// would erase every contributor on the next sync, which is the opposite of what the
// licence asks for. Merge in this project's own contributors when there are any.
const GITHUB_REPO = 'gnoviawan/termul';
const PER_PAGE = 100;

type GitHubContributor = {
  login: string;
  avatar_url: string;
};

function hasNextPage(linkHeader: string | null): boolean {
  return linkHeader?.includes('rel="next"') ?? false;
}

async function fetchContributors(): Promise<GitHubContributor[]> {
  const contributors: GitHubContributor[] = [];
  let page = 1;

  while (true) {
    const response = await fetch(
      `https://api.github.com/repos/${GITHUB_REPO}/contributors?per_page=${PER_PAGE}&page=${page}`,
      {
        headers: { Accept: 'application/vnd.github+json' },
      },
    );

    if (!response.ok) {
      throw new Error(
        `GitHub API ${response.status}: ${await response.text()}`,
      );
    }

    const batch = (await response.json()) as GitHubContributor[];
    if (batch.length === 0) {
      break;
    }

    contributors.push(...batch);

    if (batch.length < PER_PAGE || !hasNextPage(response.headers.get('link'))) {
      break;
    }

    page += 1;
  }

  return contributors;
}

function toSourceFile(contributors: GitHubContributor[]): string {
  const entries = contributors
    .filter((contributor) => !isExcludedContributor(contributor.login))
    .map(
      (contributor) =>
        `  {\n    username: '${contributor.login}',\n    avatarUrl: '${contributor.avatar_url}',\n  },`,
    )
    .join('\n');

  return `export type Contributor = {
  username: string;
  avatarUrl: string;
};

/** GitHub contributors for ${GITHUB_REPO} (generated by scripts/sync-contributors.ts). */
export const contributors: Contributor[] = [
${entries}
];
`;
}

const contributors = await fetchContributors();
const filtered = contributors.filter(
  (contributor) => !isExcludedContributor(contributor.login),
);

writeFileSync(outputPath, toSourceFile(filtered), 'utf8');

console.log(
  `Wrote ${filtered.length} contributors to ${path.relative(process.cwd(), outputPath)}` +
    (contributors.length > filtered.length
      ? ` (excluded ${contributors.length - filtered.length} bot account(s))`
      : ''),
);
