name = "termul-landing"
pages_build_output_dir = "./dist"
compatibility_date = "2026-05-31"

[[d1_databases]]
binding = "DB"
database_name = "termul"
database_id = "57a94b51-1fb7-4338-9566-c5cadeccb0f9"
preview_database_id = "DB"

[[r2_buckets]]
binding = "TESTIMONIAL_AVATARS"
bucket_name = "termul"
