#!/usr/bin/env python3
"""Executable contract tests for sync-stamped-root-lock.py."""

from __future__ import annotations

import atexit
import errno
import importlib.util
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest import mock


SCRIPT = Path(__file__).with_name("sync-stamped-root-lock.py").resolve()
PACKAGE = "termul-manager"
BYTECODE_CACHE = Path(importlib.util.cache_from_source(__file__)).resolve()


def cleanup_generated_bytecode() -> None:
    """Remove only this fixture's importlib cache and its directory when empty."""
    cache_path = BYTECODE_CACHE
    try:
        cache_path.unlink()
    except FileNotFoundError:
        pass

    try:
        cache_path.parent.rmdir()
    except FileNotFoundError:
        pass
    except OSError as error:
        if error.errno not in (errno.ENOTEMPTY, errno.EEXIST):
            raise


atexit.register(cleanup_generated_bytecode)


def write_fixture(root: Path, version: str, lock_text: str) -> tuple[Path, Path]:
    manifest = root / "Cargo.toml"
    lockfile = root / "Cargo.lock"
    manifest.write_text(
        f'[package]\nname = "{PACKAGE}"\nversion = "{version}"\nedition = "2021"\n',
        encoding="utf-8",
    )
    lockfile.write_text(lock_text, encoding="utf-8")
    return manifest, lockfile


def invoke_sync(manifest: Path, lockfile: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--manifest",
            str(manifest),
            "--lockfile",
            str(lockfile),
            "--package",
            PACKAGE,
        ],
        text=True,
        capture_output=True,
        check=False,
    )


class SyncStampedRootLockTests(unittest.TestCase):
    def test_updates_only_root_package_entry(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest, lockfile = write_fixture(
                root,
                "2.3.4",
                """# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"dependency\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n\n[[package]]\nname = \"termul-manager\"\nversion = \"0.4.10\"\ndependencies = [\n \"dependency\",\n]\n""",
            )
            before = lockfile.read_bytes()
            result = invoke_sync(manifest, lockfile)
            after = lockfile.read_bytes()
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(after, before.replace(b'version = "0.4.10"', b'version = "2.3.4"', 1))
            self.assertEqual(after.count(b'name = "termul-manager"'), 1)

    def test_preserves_dependency_versions_and_checksums(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest, lockfile = write_fixture(
                root,
                "7.8.9",
                """version = 4\n\n[[package]]\nname = \"termul-manager\"\nversion = \"99.0.0\"\nsource = \"registry+https://example.invalid/index\"\nchecksum = \"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\"\n\n[[package]]\nname = \"dependency\"\nversion = \"3.2.1\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc\"\n\n[[package]]\nname = \"termul-manager\"\nversion = \"0.4.10\"\ndependencies = [\"dependency\"]\n""",
            )
            before = lockfile.read_bytes()
            result = invoke_sync(manifest, lockfile)
            after = lockfile.read_bytes()
            expected = before.rsplit(b'version = "0.4.10"', 1)[0] + b'version = "7.8.9"' + before.rsplit(b'version = "0.4.10"', 1)[1]
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(after, expected)
            self.assertIn(b'version = "99.0.0"', after)
            self.assertEqual(after.count(b"checksum ="), 2)

    def test_rejects_missing_root_package_entry(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest, lockfile = write_fixture(
                root,
                "1.0.0",
                """version = 4\n\n[[package]]\nname = \"termul-manager\"\nversion = \"0.4.10\"\nsource = \"registry+https://example.invalid/index\"\nchecksum = \"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\"\n""",
            )
            before = lockfile.read_bytes()
            result = invoke_sync(manifest, lockfile)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("found 0", result.stderr)
            self.assertEqual(lockfile.read_bytes(), before)

    def test_rejects_ambiguous_root_package_entries(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest, lockfile = write_fixture(
                root,
                "1.0.0",
                """version = 4\n\n[[package]]\nname = \"termul-manager\"\nversion = \"0.4.10\"\n\n[[package]]\nname = \"termul-manager\"\nversion = \"0.4.11\"\n""",
            )
            before = lockfile.read_bytes()
            result = invoke_sync(manifest, lockfile)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("found 2", result.stderr)
            self.assertEqual(lockfile.read_bytes(), before)

    def test_locked_metadata_passes_after_sync(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            manifest, lockfile = write_fixture(
                root,
                "1.2.3",
                """# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"termul-manager\"\nversion = \"0.0.0\"\n""",
            )
            (root / "lib.rs").write_text("pub fn fixture() {}\n", encoding="utf-8")
            with manifest.open("a", encoding="utf-8") as handle:
                handle.write('\n[lib]\npath = "lib.rs"\n')
            synced = invoke_sync(manifest, lockfile)
            metadata = subprocess.run(
                [
                    "cargo",
                    "metadata",
                    "--locked",
                    "--manifest-path",
                    str(manifest),
                    "--format-version",
                    "1",
                    "--no-deps",
                ],
                cwd=root,
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(synced.returncode, 0, synced.stderr)
            self.assertEqual(metadata.returncode, 0, metadata.stderr)
            self.assertIn('"version":"1.2.3"', metadata.stdout)

    def _load_sync_module(self):
        spec = importlib.util.spec_from_file_location("sync_stamped_root_lock", SCRIPT)
        if spec is None or spec.loader is None:
            raise RuntimeError("unable to load sync-stamped-root-lock.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    def test_atomic_replace_succeeds_when_windows_directory_flush_unsupported(self) -> None:
        module = self._load_sync_module()
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "Cargo.lock"
            path.write_bytes(b"version = 4\n")
            unsupported = OSError(errno.EACCES, "denied")
            unsupported.winerror = 5
            with mock.patch.object(module.os, "name", "nt"), mock.patch.object(
                module,
                "_flush_windows_directory",
                side_effect=unsupported,
            ):
                module.atomic_replace(path, b"version = 5\n")
            self.assertEqual(path.read_bytes(), b"version = 5\n")

    def test_unix_directory_fsync_still_used_on_posix(self) -> None:
        module = self._load_sync_module()
        if module.os.name == "nt":
            self.skipTest("posix directory fsync contract")
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "Cargo.lock"
            path.write_bytes(b"version = 4\n")
            opened: list[int] = []
            real_open = module.os.open

            def tracking_open(target, flags, *args, **kwargs):
                opened.append(flags)
                return real_open(target, flags, *args, **kwargs)

            with mock.patch.object(module.os, "open", side_effect=tracking_open):
                module.atomic_replace(path, b"version = 5\n")
            self.assertIn(module.os.O_RDONLY, opened)
            self.assertEqual(path.read_bytes(), b"version = 5\n")


if __name__ == "__main__":
    unittest.main(verbosity=2)
